# Generated by Django X.X on 2025-11-21
# File: accounts/migrations/0001_initial.py

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
# PENTING: Import MinValueValidator dari core.validators, BUKAN dari models
import django.core.validators 


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        # Dependensi ke aplikasi autentikasi Django untuk Foreign Key ke User
        migrations.swappable_dependency(settings.AUTH_USER_MODEL), 
    ]

    operations = [
        # 1. Jenjang_Pendidikan (Master Data)
        migrations.CreateModel(
            name='Jenjang_Pendidikan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_jenjang', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Jenjang Pendidikan',
                'verbose_name_plural': 'Jenjang Pendidikan',
            },
        ),
        
        # 2. Tahun_Ajaran (Master Data)
        migrations.CreateModel(
            name='Tahun_Ajaran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_semester', models.CharField(max_length=50)),
                ('tanggal_mulai', models.DateField()),
                ('tanggal_selesai', models.DateField()),
                ('status_aktif', models.CharField(choices=[('aktif', 'Aktif'), ('nonaktif', 'Nonaktif')], default='nonaktif', max_length=10)),
            ],
            options={
                'verbose_name': 'Tahun Ajaran',
                'verbose_name_plural': 'Tahun Ajaran',
            },
        ),

        # 3. Dosen (Profile)
        migrations.CreateModel(
            name='Dosen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_dosen', models.CharField(max_length=100)),
                # OneToOneField ke User
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dosen_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Dosen',
                'verbose_name_plural': 'Dosen',
            },
        ),

        # 4. Mahasiswa (Profile)
        migrations.CreateModel(
            name='Mahasiswa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nrp', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('nama', models.CharField(max_length=100)),
                ('semester', models.CharField(max_length=20)),
                ('kelas', models.CharField(max_length=50)),
                ('sks_total_tempuh', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])), # PENGGUNAAN VALIDATOR YANG BENAR
                
                # FK ke Jenjang_Pendidikan
                ('jenjang_pendidikan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.jenjang_pendidikan')), 
                
                # OneToOneField ke User
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mahasiswa_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mahasiswa',
                'verbose_name_plural': 'Mahasiswa',
            },
        ),
        
        # 5. Kegiatan_PA
        migrations.CreateModel(
            name='Kegiatan_PA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_kegiatan', models.CharField(max_length=200)),
                ('jumlah_sks', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('total_jam_target', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                
                # FK ke Jenjang_Pendidikan
                ('jenjang_pendidikan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.jenjang_pendidikan')),
                
                # FK ke Tahun_Ajaran
                ('tahun_ajaran', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.tahun_ajaran')),
            ],
            options={
                'verbose_name': 'Kegiatan PA',
                'verbose_name_plural': 'Kegiatan PA',
            },
        ),

        # 6. FotoWajah
        migrations.CreateModel(
            name='FotoWajah',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.ImageField(upload_to='dataset_wajah/')),
                # FK ke Mahasiswa
                ('mahasiswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foto_wajah', to='accounts.mahasiswa')),
            ],
            options={
                'verbose_name': 'Foto Wajah',
                'verbose_name_plural': 'Foto Wajah',
            },
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Nama Semester (Lookup)',
                'verbose_name_plural': 'Nama Semester (Lookup)',
            },
        ),
        # 7. Pengajuan_Pendaftaran
        migrations.CreateModel(
            name='Pengajuan_Pendaftaran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_pengajuan', models.CharField(choices=[('pending', 'Pending'), ('disetujui', 'Disetujui'), ('ditolak', 'Ditolak')], default='pending', max_length=10)),
                ('alasan_penolakan', models.TextField(blank=True, null=True)),
                # OneToOneField ke Mahasiswa
                ('mahasiswa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.mahasiswa')),
            ],
            options={
                'verbose_name': 'Pengajuan Pendaftaran',
                'verbose_name_plural': 'Pengajuan Pendaftaran',
            },
        ),

        # 8. Presensi
        migrations.CreateModel(
            name='Presensi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal_presensi', models.DateField()),
                ('jam_checkin', models.TimeField(blank=True, null=True)),
                ('jam_checkout', models.TimeField(blank=True, null=True)),
                ('foto_checkin', models.ImageField(blank=True, null=True, upload_to='presensi/checkin/')),
                ('foto_checkout', models.ImageField(blank=True, null=True, upload_to='presensi/checkout/')),
                # FK ke Kegiatan_PA
                ('kegiatan_pa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.kegiatan_pa')),
                # FK ke Mahasiswa
                ('mahasiswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.mahasiswa')),
            ],
            options={
                'verbose_name': 'Presensi',
                'verbose_name_plural': 'Presensi',
            },
        ),

        # 9. Durasi
        migrations.CreateModel(
            name='Durasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waktu_durasi', models.DurationField()),
                # OneToOneField ke Presensi
                ('presensi', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.presensi')),
            ],
            options={
                'verbose_name': 'Durasi Presensi',
                'verbose_name_plural': 'Durasi Presensi',
            },
        ),

        # 10. Mahasiswa_Dosen (Relasi Many-to-Many Pembimbing)
        migrations.CreateModel(
            name='Mahasiswa_Dosen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipe_pembimbing', models.CharField(choices=[('pembimbing1', 'Pembimbing 1'), ('pembimbing2', 'Pembimbing 2'), ('pembimbing3', 'Pembimbing 3')], max_length=20)),
                # FK ke Dosen
                ('dosen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.dosen')),
                # FK ke Mahasiswa
                ('mahasiswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.mahasiswa')),
            ],
            options={
                'verbose_name': 'Mahasiswa Dosen Pembimbing',
                'verbose_name_plural': 'Mahasiswa Dosen Pembimbing',
                'unique_together': {('mahasiswa', 'tipe_pembimbing')}, 
            },
        ),

        # 11. Status_Pemenuhan_SKS
        migrations.CreateModel(
            name='Status_Pemenuhan_SKS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jumlah_sks', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('jam_target', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('jam_tercapai', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('status_pemenuhan', models.CharField(choices=[('belum memenuhi', 'Belum Memenuhi'), ('memenuhi', 'Memenuhi')], default='belum memenuhi', max_length=20)),
                # FK ke Kegiatan_PA
                ('kegiatan_pa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.kegiatan_pa')),
                # FK ke Mahasiswa
                ('mahasiswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.mahasiswa')),
            ],
            options={
                'verbose_name': 'Status Pemenuhan SKS',
                'verbose_name_plural': 'Status Pemenuhan SKS',
                'unique_together': {('mahasiswa', 'kegiatan_pa')}, 
            },
        ),
    ]