# Generated by Django 4.2.25 on 2026-04-24 09:31

import accounts.models
from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Akun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('nrp', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='NRP')),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('mahasiswa', 'Student')], default='mahasiswa', max_length=20, verbose_name='Role')),
                ('status_akun', models.CharField(choices=[('aktif', 'Active'), ('nonaktif', 'Inactive')], default='aktif', max_length=10, verbose_name='Account Status')),
                ('nama_lengkap', models.CharField(blank=True, max_length=150, verbose_name='Full Name')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Account',
                'verbose_name_plural': 'Accounts',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Dosen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nip', models.CharField(max_length=30, unique=True, verbose_name='NIP')),
                ('nama_dosen', models.CharField(max_length=150, verbose_name='Lecturer Name')),
                ('prodi', models.CharField(max_length=100, verbose_name='Study Program')),
            ],
            options={
                'verbose_name': 'Lecturer',
                'verbose_name_plural': 'Lecturers',
            },
        ),
        migrations.CreateModel(
            name='Jenjang_Pendidikan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_jenjang', models.CharField(max_length=50, unique=True, verbose_name='Education Level')),
            ],
            options={
                'verbose_name': 'Education Level',
                'verbose_name_plural': 'Education Levels',
            },
        ),
        migrations.CreateModel(
            name='Kegiatan_PA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_kegiatan', models.CharField(max_length=200, verbose_name='Activity Name')),
                ('jumlah_sks', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Credits')),
                ('total_jam_minggu', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Total Hours per Week')),
                ('target_jam', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Target Hours')),
                ('jenjang_pendidikan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.jenjang_pendidikan')),
            ],
            options={
                'verbose_name': 'PA Activity',
                'verbose_name_plural': 'PA Activities',
            },
        ),
        migrations.CreateModel(
            name='Mahasiswa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nim', models.CharField(max_length=20, unique=True, verbose_name='Student ID')),
                ('kelas', models.CharField(max_length=50, verbose_name='Class')),
                ('sks_total_tempuh', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Total Credits Taken')),
                ('angkatan', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(accounts.models.current_year)], verbose_name='Batch Year')),
                ('jurusan', models.CharField(blank=True, max_length=255, null=True, verbose_name='Major')),
                ('jenjang_pendidikan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.jenjang_pendidikan')),
                ('kegiatan_pa', models.ManyToManyField(blank=True, to='accounts.kegiatan_pa')),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Students',
            },
        ),
        migrations.CreateModel(
            name='Presensi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal_presensi', models.DateField(verbose_name='Attendance Date')),
                ('jam_checkin', models.TimeField(blank=True, null=True, verbose_name='Check-in Time')),
                ('jam_checkout', models.TimeField(blank=True, null=True, verbose_name='Check-out Time')),
                ('foto_checkin', models.ImageField(blank=True, null=True, upload_to='presensi/checkin/', verbose_name='Check-in Photo')),
                ('foto_checkout', models.ImageField(blank=True, null=True, upload_to='presensi/checkout/', verbose_name='Check-out Photo')),
                ('terakhir_terdeteksi', models.TimeField(blank=True, null=True, verbose_name='Last Detected Time')),
                ('last_verified_at', models.DateTimeField(blank=True, null=True, verbose_name='Last Verified At')),
                ('failure_count', models.IntegerField(default=0, verbose_name='Failure Count')),
                ('session_status', models.CharField(choices=[('active', 'Active'), ('verifying', 'Verifying'), ('auto_checkout', 'Auto Checked Out'), ('completed', 'Completed')], default='active', max_length=20, verbose_name='Session Status')),
                ('kegiatan_pa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.kegiatan_pa')),
                ('mahasiswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.mahasiswa')),
            ],
        ),
        migrations.CreateModel(
            name='Tahun_Ajaran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_tahun_ajaran', models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='Academic Year Name')),
                ('tanggal_mulai', models.DateField(verbose_name='Start Date')),
                ('tanggal_selesai', models.DateField(verbose_name='End Date')),
                ('status_aktif', models.CharField(choices=[('aktif', 'Active'), ('nonaktif', 'Inactive')], default='nonaktif', max_length=10, verbose_name='Active Status')),
            ],
            options={
                'verbose_name': 'Academic Year',
                'verbose_name_plural': 'Academic Years',
            },
        ),
        migrations.CreateModel(
            name='VerificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=False)),
                ('is_liveness_real', models.BooleanField(default=False)),
                ('failure_count', models.IntegerField(default=0)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='presensi/verification/', verbose_name='Verification Photo')),
                ('mahasiswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.mahasiswa')),
                ('presensi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='verification_logs', to='accounts.presensi')),
            ],
            options={
                'verbose_name': 'Presence Verification Log',
                'verbose_name_plural': 'Presence Verification Logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jenjang', models.CharField(choices=[('D3', 'D3 - Diploma 3'), ('D4', 'D4 - Diploma 4'), ('S2', 'S2 - Magister')], max_length=10, verbose_name='Education Level')),
                ('nomor_semester', models.PositiveSmallIntegerField(verbose_name='Semester Number')),
                ('nama_semester', models.CharField(max_length=20, verbose_name='Semester Name')),
            ],
            options={
                'verbose_name': 'Semester',
                'verbose_name_plural': 'Semesters',
                'unique_together': {('jenjang', 'nomor_semester')},
            },
        ),
        migrations.CreateModel(
            name='Prodi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode_prodi', models.CharField(help_text='Example: D4-TE, D3-TI, S2-TE', max_length=20, unique=True, verbose_name='Program Code')),
                ('nama_prodi', models.CharField(help_text='Full name of study program', max_length=255, verbose_name='Program Name')),
                ('nama_singkat', models.CharField(blank=True, help_text='Short name/abbreviation', max_length=50, verbose_name='Short Name')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this study program is still active', verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('jenjang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prodi_set', to='accounts.jenjang_pendidikan', verbose_name='Education Level')),
            ],
            options={
                'verbose_name': 'Study Program',
                'verbose_name_plural': 'Study Programs',
                'ordering': ['jenjang__nama_jenjang', 'kode_prodi'],
                'unique_together': {('jenjang', 'kode_prodi')},
            },
        ),
        migrations.CreateModel(
            name='Pengajuan_Pendaftaran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_pengajuan', models.CharField(choices=[('pending', 'Pending'), ('disetujui', 'Approved'), ('ditolak', 'Rejected')], default='pending', max_length=10, verbose_name='Submission Status')),
                ('alasan_penolakan', models.TextField(blank=True, null=True, verbose_name='Rejection Reason')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('mahasiswa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.mahasiswa')),
            ],
            options={
                'verbose_name': 'Registration Submission',
                'verbose_name_plural': 'Registration Submissions',
            },
        ),
        migrations.AddField(
            model_name='mahasiswa',
            name='prodi',
            field=models.ForeignKey(blank=True, help_text='Selected study program based on education level', null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.prodi', verbose_name='Study Program'),
        ),
        migrations.AddField(
            model_name='mahasiswa',
            name='semester',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.semester'),
        ),
        migrations.AddField(
            model_name='mahasiswa',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mahasiswa_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='kegiatan_pa',
            name='tahun_ajaran',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.tahun_ajaran'),
        ),
        migrations.CreateModel(
            name='FotoWajah',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.ImageField(upload_to='dataset_wajah/', verbose_name='File Path')),
                ('keterangan', models.CharField(blank=True, max_length=255, null=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('mahasiswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foto_wajah', to='accounts.mahasiswa')),
            ],
            options={
                'verbose_name': 'Face Photo',
                'verbose_name_plural': 'Face Photos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Durasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waktu_durasi', models.DurationField(verbose_name='Duration')),
                ('presensi', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.presensi')),
            ],
            options={
                'verbose_name': 'Attendance Duration',
                'verbose_name_plural': 'Attendance Durations',
            },
        ),
        migrations.CreateModel(
            name='Status_Pemenuhan_SKS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jumlah_sks', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Credits Earned')),
                ('jam_target', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Target Hours')),
                ('jam_tercapai', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Achieved Hours')),
                ('status_pemenuhan', models.CharField(choices=[('belum memenuhi', 'Not Fulfilled'), ('memenuhi', 'Fulfilled')], default='belum memenuhi', max_length=20, verbose_name='Fulfillment Status')),
                ('kegiatan_pa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.kegiatan_pa')),
                ('mahasiswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.mahasiswa')),
            ],
            options={
                'verbose_name': 'Credit Fulfillment Status',
                'verbose_name_plural': 'Credit Fulfillment Statuses',
                'unique_together': {('mahasiswa', 'kegiatan_pa')},
            },
        ),
        migrations.CreateModel(
            name='Mahasiswa_Dosen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipe_pembimbing', models.CharField(choices=[('pembimbing1', 'Supervisor 1'), ('pembimbing2', 'Supervisor 2'), ('pembimbing3', 'Supervisor 3')], max_length=20, verbose_name='Supervisor Type')),
                ('dosen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.dosen')),
                ('mahasiswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.mahasiswa')),
            ],
            options={
                'verbose_name': 'Student Lecturer',
                'verbose_name_plural': 'Student Lecturers',
                'unique_together': {('mahasiswa', 'tipe_pembimbing')},
            },
        ),
    ]
