# Generated by Django 5.2.8 on 2025-11-22 13:00

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dosen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nip', models.CharField(max_length=30, unique=True)),
                ('nama_dosen', models.CharField(max_length=150)),
                ('prodi', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Dosen',
            },
        ),
        migrations.CreateModel(
            name='Jenjang_Pendidikan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_jenjang', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Jenjang Pendidikan',
                'verbose_name_plural': 'Jenjang Pendidikan',
            },
        ),
        migrations.CreateModel(
            name='Tahun_Ajaran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_semester', models.CharField(max_length=50)),
                ('tanggal_mulai', models.DateField()),
                ('tanggal_selesai', models.DateField()),
                ('status_aktif', models.CharField(choices=[('aktif', 'Aktif'), ('nonaktif', 'Nonaktif')], default='nonaktif', max_length=10)),
            ],
            options={
                'verbose_name': 'Tahun Ajaran',
                'verbose_name_plural': 'Tahun Ajaran',
            },
        ),
        migrations.CreateModel(
            name='Akun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('nrp', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('mahasiswa', 'Mahasiswa')], default='mahasiswa', max_length=20)),
                ('status_akun', models.CharField(choices=[('aktif', 'Aktif'), ('nonaktif', 'Nonaktif')], default='aktif', max_length=10)),
                ('nama_lengkap', models.CharField(blank=True, max_length=150)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Akun',
                'verbose_name_plural': 'Akun',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Kegiatan_PA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_kegiatan', models.CharField(max_length=200)),
                ('jumlah_sks', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('total_jam_minggu', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('target_jam', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('jenjang_pendidikan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.jenjang_pendidikan')),
                ('tahun_ajaran', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.tahun_ajaran')),
            ],
            options={
                'verbose_name': 'Kegiatan PA',
                'verbose_name_plural': 'Kegiatan PA',
            },
        ),
        migrations.CreateModel(
            name='Mahasiswa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(max_length=20)),
                ('kelas', models.CharField(max_length=50)),
                ('sks_total_tempuh', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('jenjang_pendidikan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.jenjang_pendidikan')),
                ('kegiatan_pa', models.ManyToManyField(blank=True, to='accounts.kegiatan_pa')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mahasiswa_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mahasiswa',
                'verbose_name_plural': 'Mahasiswa',
            },
        ),
        migrations.CreateModel(
            name='FotoWajah',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.ImageField(upload_to='dataset_wajah/')),
                ('mahasiswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foto_wajah', to='accounts.mahasiswa')),
            ],
            options={
                'verbose_name': 'Foto Wajah',
                'verbose_name_plural': 'Foto Wajah',
            },
        ),
        migrations.CreateModel(
            name='Pengajuan_Pendaftaran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_pengajuan', models.CharField(choices=[('pending', 'Pending'), ('disetujui', 'Disetujui'), ('ditolak', 'Ditolak')], default='pending', max_length=10)),
                ('alasan_penolakan', models.TextField(blank=True, null=True)),
                ('mahasiswa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.mahasiswa')),
            ],
            options={
                'verbose_name': 'Pengajuan Pendaftaran',
                'verbose_name_plural': 'Pengajuan Pendaftaran',
            },
        ),
        migrations.CreateModel(
            name='Presensi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal_presensi', models.DateField()),
                ('jam_checkin', models.TimeField(blank=True, null=True)),
                ('jam_checkout', models.TimeField(blank=True, null=True)),
                ('foto_checkin', models.ImageField(blank=True, null=True, upload_to='presensi/checkin/')),
                ('foto_checkout', models.ImageField(blank=True, null=True, upload_to='presensi/checkout/')),
                ('kegiatan_pa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.kegiatan_pa')),
                ('mahasiswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.mahasiswa')),
            ],
            options={
                'verbose_name': 'Presensi',
                'verbose_name_plural': 'Presensi',
            },
        ),
        migrations.CreateModel(
            name='Durasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waktu_durasi', models.DurationField()),
                ('presensi', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.presensi')),
            ],
            options={
                'verbose_name': 'Durasi Presensi',
                'verbose_name_plural': 'Durasi Presensi',
            },
        ),
        migrations.CreateModel(
            name='Mahasiswa_Dosen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipe_pembimbing', models.CharField(choices=[('pembimbing1', 'Pembimbing 1'), ('pembimbing2', 'Pembimbing 2'), ('pembimbing3', 'Pembimbing 3')], max_length=20)),
                ('dosen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.dosen')),
                ('mahasiswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.mahasiswa')),
            ],
            options={
                'verbose_name': 'Mahasiswa Dosen Pembimbing',
                'verbose_name_plural': 'Mahasiswa Dosen Pembimbing',
                'unique_together': {('mahasiswa', 'tipe_pembimbing')},
            },
        ),
        migrations.CreateModel(
            name='Status_Pemenuhan_SKS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jumlah_sks', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('jam_target', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('jam_tercapai', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('status_pemenuhan', models.CharField(choices=[('belum memenuhi', 'Belum Memenuhi'), ('memenuhi', 'Memenuhi')], default='belum memenuhi', max_length=20)),
                ('kegiatan_pa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.kegiatan_pa')),
                ('mahasiswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.mahasiswa')),
            ],
            options={
                'verbose_name': 'Status Pemenuhan SKS',
                'verbose_name_plural': 'Status Pemenuhan SKS',
                'unique_together': {('mahasiswa', 'kegiatan_pa')},
            },
        ),
    ]
