# Generated by Django 5.2.8 on 2025-12-04 05:58

import accounts.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_semester', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'verbose_name': 'Semester',
                'verbose_name_plural': 'Semester',
            },
        ),
        migrations.RemoveField(
            model_name='tahun_ajaran',
            name='nama_semester',
        ),
        migrations.AddField(
            model_name='mahasiswa',
            name='angkatan',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(accounts.models.current_year)]),
        ),
        migrations.AddField(
            model_name='mahasiswa',
            name='jurusan',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='kegiatan_pa',
            name='semester',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.semester'),
        ),
        migrations.AlterField(
            model_name='mahasiswa',
            name='semester',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.semester'),
        ),
    ]
