# Generated by Django 4.2.25 on 2026-04-25 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kelas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_kelas', models.CharField(max_length=50, verbose_name='Class Name')),
                ('kode_kelas', models.CharField(max_length=20, unique=True, verbose_name='Class Code')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('jenjang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kelas_set', to='accounts.jenjang_pendidikan', verbose_name='Education Level')),
                ('prodi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kelas_set', to='accounts.prodi', verbose_name='Study Program')),
            ],
            options={
                'verbose_name': 'Class',
                'verbose_name_plural': 'Classes',
                'ordering': ['jenjang__nama_jenjang', 'prodi__nama_prodi', 'nama_kelas'],
            },
        ),
        migrations.AlterField(
            model_name='mahasiswa',
            name='kelas',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.kelas', verbose_name='Class'),
        ),
    ]
