# Generated by Django 4.2.25 on 2026-04-25 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_kelas_alter_mahasiswa_kelas'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kelas',
            options={},
        ),
        migrations.AlterField(
            model_name='kelas',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='kelas',
            name='jenjang',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.jenjang_pendidikan'),
        ),
        migrations.AlterField(
            model_name='kelas',
            name='kode_kelas',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='kelas',
            name='nama_kelas',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='kelas',
            name='prodi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.prodi'),
        ),
    ]
