# Generated by Django 5.2.8 on 2025-12-04 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_semester_remove_tahun_ajaran_nama_semester_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kegiatan_pa',
            name='semester',
        ),
        migrations.AddField(
            model_name='tahun_ajaran',
            name='nama_tahun_ajaran',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
