# Generated by Django 4.2.25 on 2026-04-25 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_kelas_options_alter_kelas_is_active_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kelas',
            options={'ordering': ['nama_kelas'], 'verbose_name': 'Class', 'verbose_name_plural': 'Classes'},
        ),
        migrations.RemoveField(
            model_name='kelas',
            name='jenjang',
        ),
        migrations.RemoveField(
            model_name='kelas',
            name='prodi',
        ),
        migrations.AlterField(
            model_name='kelas',
            name='kode_kelas',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='kelas',
            name='nama_kelas',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
