# Generated by Django 5.2.8 on 2025-12-04 16:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_kegiatan_pa_semester_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fotowajah',
            options={'ordering': ['-created_at'], 'verbose_name': 'Foto Wajah', 'verbose_name_plural': 'Foto Wajah'},
        ),
        migrations.AddField(
            model_name='fotowajah',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fotowajah',
            name='keterangan',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
