# Generated by Django 4.2.25 on 2026-04-26 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_kelas_options_remove_kelas_jenjang_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mahasiswa',
            name='foto_ktm',
            field=models.ImageField(blank=True, null=True, upload_to='ktm/', verbose_name='Student ID Card (KTM)'),
        ),
    ]
