# Generated by Django 5.2.8 on 2025-12-09 10:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_fotowajah_options_fotowajah_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pengajuan_pendaftaran',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pengajuan_pendaftaran',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
