# Generated by Django 4.2.25 on 2026-04-28 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_mahasiswa_foto_ktm'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='presensi',
            name='failure_count',
        ),
        migrations.AddField(
            model_name='presensi',
            name='consecutive_failures',
            field=models.IntegerField(default=0, help_text='Jumlah kegagalan verifikasi BERTURUT-TURUT'),
        ),
    ]
