# Generated by Django 5.2.8 on 2025-12-09 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_pengajuan_pendaftaran_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mahasiswa',
            name='nim',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
