# Generated by Django 4.2.25 on 2026-04-28 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_presensi_failure_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='presensi',
            name='sudah_verifikasi',
            field=models.BooleanField(default=False, help_text='Apakah sudah pernah verifikasi (monitoring dimulai)'),
        ),
    ]
