# Generated by Django 4.2.25 on 2026-04-30 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_presensi_sudah_verifikasi'),
    ]

    operations = [
        migrations.AddField(
            model_name='presensi',
            name='monitoring_deadline',
            field=models.DateTimeField(blank=True, help_text='Batas waktu untuk memulai monitoring (check-in + 10 menit)', null=True, verbose_name='Monitoring Deadline'),
        ),
        migrations.AlterField(
            model_name='presensi',
            name='session_status',
            field=models.CharField(choices=[('waiting_monitoring', 'Waiting for Monitoring'), ('monitoring_active', 'Monitoring Active'), ('auto_checkout', 'Auto Checked Out'), ('completed', 'Completed')], default='waiting_monitoring', max_length=20, verbose_name='Session Status'),
        ),
    ]
