# Generated by Django 5.2.8 on 2025-12-10 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_mahasiswa_nim'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='pengajuan_pendaftaran',
            table='pengajuan_pendaftaran',
        ),
    ]
