# Generated by Django 4.2.25 on 2026-04-30 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_presensi_monitoring_deadline_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presensi',
            name='consecutive_failures',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='presensi',
            name='monitoring_deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='presensi',
            name='session_status',
            field=models.CharField(choices=[('waiting_monitoring', 'Menunggu Monitoring'), ('monitoring_active', 'Monitoring Aktif'), ('auto_checkout', 'Auto Checkout'), ('completed', 'Selesai')], default='waiting_monitoring', max_length=20),
        ),
        migrations.AlterField(
            model_name='presensi',
            name='sudah_verifikasi',
            field=models.BooleanField(default=False),
        ),
    ]
