# Generated by Django 5.2.8 on 2025-12-13 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_pengajuan_pendaftaran_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='akun',
            name='first_name_en',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='first name'),
        ),
        migrations.AddField(
            model_name='akun',
            name='first_name_ind',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='first name'),
        ),
        migrations.AddField(
            model_name='akun',
            name='last_name_en',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='last name'),
        ),
        migrations.AddField(
            model_name='akun',
            name='last_name_ind',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='last name'),
        ),
        migrations.AddField(
            model_name='akun',
            name='nama_lengkap_en',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='akun',
            name='nama_lengkap_ind',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='dosen',
            name='nama_dosen_en',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='dosen',
            name='nama_dosen_ind',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='dosen',
            name='prodi_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='dosen',
            name='prodi_ind',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='fotowajah',
            name='keterangan_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='fotowajah',
            name='keterangan_ind',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='jenjang_pendidikan',
            name='nama_jenjang_en',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='jenjang_pendidikan',
            name='nama_jenjang_ind',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='kegiatan_pa',
            name='nama_kegiatan_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='kegiatan_pa',
            name='nama_kegiatan_ind',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='mahasiswa',
            name='jurusan_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='mahasiswa',
            name='jurusan_ind',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='mahasiswa',
            name='kelas_en',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='mahasiswa',
            name='kelas_ind',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='pengajuan_pendaftaran',
            name='alasan_penolakan_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pengajuan_pendaftaran',
            name='alasan_penolakan_ind',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='semester',
            name='nama_semester_en',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='semester',
            name='nama_semester_ind',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='tahun_ajaran',
            name='nama_tahun_ajaran_en',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tahun_ajaran',
            name='nama_tahun_ajaran_ind',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterModelTable(
            name='pengajuan_pendaftaran',
            table=None,
        ),
    ]
