# Generated by Django 5.2.8 on 2025-12-13 18:48

import accounts.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_akun_first_name_en_akun_first_name_ind_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='akun',
            options={'verbose_name': 'Account', 'verbose_name_plural': 'Accounts'},
        ),
        migrations.AlterModelOptions(
            name='dosen',
            options={'verbose_name': 'Lecturer', 'verbose_name_plural': 'Lecturers'},
        ),
        migrations.AlterModelOptions(
            name='durasi',
            options={'verbose_name': 'Attendance Duration', 'verbose_name_plural': 'Attendance Durations'},
        ),
        migrations.AlterModelOptions(
            name='fotowajah',
            options={'ordering': ['-created_at'], 'verbose_name': 'Face Photo', 'verbose_name_plural': 'Face Photos'},
        ),
        migrations.AlterModelOptions(
            name='jenjang_pendidikan',
            options={'verbose_name': 'Education Level', 'verbose_name_plural': 'Education Levels'},
        ),
        migrations.AlterModelOptions(
            name='kegiatan_pa',
            options={'verbose_name': 'PA Activity', 'verbose_name_plural': 'PA Activities'},
        ),
        migrations.AlterModelOptions(
            name='mahasiswa',
            options={'verbose_name': 'Student', 'verbose_name_plural': 'Students'},
        ),
        migrations.AlterModelOptions(
            name='mahasiswa_dosen',
            options={'verbose_name': 'Student Lecturer', 'verbose_name_plural': 'Student Lecturers'},
        ),
        migrations.AlterModelOptions(
            name='pengajuan_pendaftaran',
            options={'verbose_name': 'Registration Submission', 'verbose_name_plural': 'Registration Submissions'},
        ),
        migrations.AlterModelOptions(
            name='presensi',
            options={'verbose_name': 'Attendance', 'verbose_name_plural': 'Attendances'},
        ),
        migrations.AlterModelOptions(
            name='semester',
            options={'verbose_name': 'Semester', 'verbose_name_plural': 'Semesters'},
        ),
        migrations.AlterModelOptions(
            name='status_pemenuhan_sks',
            options={'verbose_name': 'Credit Fulfillment Status', 'verbose_name_plural': 'Credit Fulfillment Statuses'},
        ),
        migrations.AlterModelOptions(
            name='tahun_ajaran',
            options={'verbose_name': 'Academic Year', 'verbose_name_plural': 'Academic Years'},
        ),
        migrations.AlterField(
            model_name='akun',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='akun',
            name='nama_lengkap',
            field=models.CharField(blank=True, max_length=150, verbose_name='Full Name'),
        ),
        migrations.AlterField(
            model_name='akun',
            name='nama_lengkap_en',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Full Name'),
        ),
        migrations.AlterField(
            model_name='akun',
            name='nama_lengkap_ind',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Full Name'),
        ),
        migrations.AlterField(
            model_name='akun',
            name='nrp',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='NRP'),
        ),
        migrations.AlterField(
            model_name='akun',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('mahasiswa', 'Student')], default='mahasiswa', max_length=20, verbose_name='Role'),
        ),
        migrations.AlterField(
            model_name='akun',
            name='status_akun',
            field=models.CharField(choices=[('aktif', 'Active'), ('nonaktif', 'Inactive')], default='aktif', max_length=10, verbose_name='Account Status'),
        ),
        migrations.AlterField(
            model_name='dosen',
            name='nama_dosen',
            field=models.CharField(max_length=150, verbose_name='Lecturer Name'),
        ),
        migrations.AlterField(
            model_name='dosen',
            name='nama_dosen_en',
            field=models.CharField(max_length=150, null=True, verbose_name='Lecturer Name'),
        ),
        migrations.AlterField(
            model_name='dosen',
            name='nama_dosen_ind',
            field=models.CharField(max_length=150, null=True, verbose_name='Lecturer Name'),
        ),
        migrations.AlterField(
            model_name='dosen',
            name='nip',
            field=models.CharField(max_length=30, unique=True, verbose_name='NIP'),
        ),
        migrations.AlterField(
            model_name='dosen',
            name='prodi',
            field=models.CharField(max_length=100, verbose_name='Study Program'),
        ),
        migrations.AlterField(
            model_name='dosen',
            name='prodi_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Study Program'),
        ),
        migrations.AlterField(
            model_name='dosen',
            name='prodi_ind',
            field=models.CharField(max_length=100, null=True, verbose_name='Study Program'),
        ),
        migrations.AlterField(
            model_name='durasi',
            name='waktu_durasi',
            field=models.DurationField(verbose_name='Duration'),
        ),
        migrations.AlterField(
            model_name='fotowajah',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='fotowajah',
            name='file_path',
            field=models.ImageField(upload_to='dataset_wajah/', verbose_name='File Path'),
        ),
        migrations.AlterField(
            model_name='fotowajah',
            name='keterangan',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='fotowajah',
            name='keterangan_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='fotowajah',
            name='keterangan_ind',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='jenjang_pendidikan',
            name='nama_jenjang',
            field=models.CharField(max_length=50, unique=True, verbose_name='Education Level'),
        ),
        migrations.AlterField(
            model_name='jenjang_pendidikan',
            name='nama_jenjang_en',
            field=models.CharField(max_length=50, null=True, unique=True, verbose_name='Education Level'),
        ),
        migrations.AlterField(
            model_name='jenjang_pendidikan',
            name='nama_jenjang_ind',
            field=models.CharField(max_length=50, null=True, unique=True, verbose_name='Education Level'),
        ),
        migrations.AlterField(
            model_name='kegiatan_pa',
            name='jumlah_sks',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Credits'),
        ),
        migrations.AlterField(
            model_name='kegiatan_pa',
            name='nama_kegiatan',
            field=models.CharField(max_length=200, verbose_name='Activity Name'),
        ),
        migrations.AlterField(
            model_name='kegiatan_pa',
            name='nama_kegiatan_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Activity Name'),
        ),
        migrations.AlterField(
            model_name='kegiatan_pa',
            name='nama_kegiatan_ind',
            field=models.CharField(max_length=200, null=True, verbose_name='Activity Name'),
        ),
        migrations.AlterField(
            model_name='kegiatan_pa',
            name='target_jam',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Target Hours'),
        ),
        migrations.AlterField(
            model_name='kegiatan_pa',
            name='total_jam_minggu',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Total Hours per Week'),
        ),
        migrations.AlterField(
            model_name='mahasiswa',
            name='angkatan',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(accounts.models.current_year)], verbose_name='Batch Year'),
        ),
        migrations.AlterField(
            model_name='mahasiswa',
            name='jurusan',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Major'),
        ),
        migrations.AlterField(
            model_name='mahasiswa',
            name='jurusan_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Major'),
        ),
        migrations.AlterField(
            model_name='mahasiswa',
            name='jurusan_ind',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Major'),
        ),
        migrations.AlterField(
            model_name='mahasiswa',
            name='kelas',
            field=models.CharField(max_length=50, verbose_name='Class'),
        ),
        migrations.AlterField(
            model_name='mahasiswa',
            name='kelas_en',
            field=models.CharField(max_length=50, null=True, verbose_name='Class'),
        ),
        migrations.AlterField(
            model_name='mahasiswa',
            name='kelas_ind',
            field=models.CharField(max_length=50, null=True, verbose_name='Class'),
        ),
        migrations.AlterField(
            model_name='mahasiswa',
            name='nim',
            field=models.CharField(max_length=20, unique=True, verbose_name='Student ID'),
        ),
        migrations.AlterField(
            model_name='mahasiswa',
            name='sks_total_tempuh',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Total Credits Taken'),
        ),
        migrations.AlterField(
            model_name='mahasiswa_dosen',
            name='tipe_pembimbing',
            field=models.CharField(choices=[('pembimbing1', 'Supervisor 1'), ('pembimbing2', 'Supervisor 2'), ('pembimbing3', 'Supervisor 3')], max_length=20, verbose_name='Supervisor Type'),
        ),
        migrations.AlterField(
            model_name='pengajuan_pendaftaran',
            name='alasan_penolakan',
            field=models.TextField(blank=True, null=True, verbose_name='Rejection Reason'),
        ),
        migrations.AlterField(
            model_name='pengajuan_pendaftaran',
            name='alasan_penolakan_en',
            field=models.TextField(blank=True, null=True, verbose_name='Rejection Reason'),
        ),
        migrations.AlterField(
            model_name='pengajuan_pendaftaran',
            name='alasan_penolakan_ind',
            field=models.TextField(blank=True, null=True, verbose_name='Rejection Reason'),
        ),
        migrations.AlterField(
            model_name='pengajuan_pendaftaran',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='pengajuan_pendaftaran',
            name='status_pengajuan',
            field=models.CharField(choices=[('pending', 'Pending'), ('disetujui', 'Approved'), ('ditolak', 'Rejected')], default='pending', max_length=10, verbose_name='Submission Status'),
        ),
        migrations.AlterField(
            model_name='pengajuan_pendaftaran',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='presensi',
            name='foto_checkin',
            field=models.ImageField(blank=True, null=True, upload_to='presensi/checkin/', verbose_name='Check-in Photo'),
        ),
        migrations.AlterField(
            model_name='presensi',
            name='foto_checkout',
            field=models.ImageField(blank=True, null=True, upload_to='presensi/checkout/', verbose_name='Check-out Photo'),
        ),
        migrations.AlterField(
            model_name='presensi',
            name='jam_checkin',
            field=models.TimeField(blank=True, null=True, verbose_name='Check-in Time'),
        ),
        migrations.AlterField(
            model_name='presensi',
            name='jam_checkout',
            field=models.TimeField(blank=True, null=True, verbose_name='Check-out Time'),
        ),
        migrations.AlterField(
            model_name='presensi',
            name='tanggal_presensi',
            field=models.DateField(verbose_name='Attendance Date'),
        ),
        migrations.AlterField(
            model_name='semester',
            name='nama_semester',
            field=models.CharField(max_length=20, unique=True, verbose_name='Semester Name'),
        ),
        migrations.AlterField(
            model_name='semester',
            name='nama_semester_en',
            field=models.CharField(max_length=20, null=True, unique=True, verbose_name='Semester Name'),
        ),
        migrations.AlterField(
            model_name='semester',
            name='nama_semester_ind',
            field=models.CharField(max_length=20, null=True, unique=True, verbose_name='Semester Name'),
        ),
        migrations.AlterField(
            model_name='status_pemenuhan_sks',
            name='jam_target',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Target Hours'),
        ),
        migrations.AlterField(
            model_name='status_pemenuhan_sks',
            name='jam_tercapai',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Achieved Hours'),
        ),
        migrations.AlterField(
            model_name='status_pemenuhan_sks',
            name='jumlah_sks',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Credits Earned'),
        ),
        migrations.AlterField(
            model_name='status_pemenuhan_sks',
            name='status_pemenuhan',
            field=models.CharField(choices=[('belum memenuhi', 'Not Fulfilled'), ('memenuhi', 'Fulfilled')], default='belum memenuhi', max_length=20, verbose_name='Fulfillment Status'),
        ),
        migrations.AlterField(
            model_name='tahun_ajaran',
            name='nama_tahun_ajaran',
            field=models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='Academic Year Name'),
        ),
        migrations.AlterField(
            model_name='tahun_ajaran',
            name='nama_tahun_ajaran_en',
            field=models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='Academic Year Name'),
        ),
        migrations.AlterField(
            model_name='tahun_ajaran',
            name='nama_tahun_ajaran_ind',
            field=models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='Academic Year Name'),
        ),
        migrations.AlterField(
            model_name='tahun_ajaran',
            name='status_aktif',
            field=models.CharField(choices=[('aktif', 'Active'), ('nonaktif', 'Inactive')], default='nonaktif', max_length=10, verbose_name='Active Status'),
        ),
        migrations.AlterField(
            model_name='tahun_ajaran',
            name='tanggal_mulai',
            field=models.DateField(verbose_name='Start Date'),
        ),
        migrations.AlterField(
            model_name='tahun_ajaran',
            name='tanggal_selesai',
            field=models.DateField(verbose_name='End Date'),
        ),
    ]
