# Generated by Django 5.2.8 on 2026-02-03 05:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_akun_options_alter_dosen_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='akun',
            name='first_name_en',
        ),
        migrations.RemoveField(
            model_name='akun',
            name='first_name_ind',
        ),
        migrations.RemoveField(
            model_name='akun',
            name='last_name_en',
        ),
        migrations.RemoveField(
            model_name='akun',
            name='last_name_ind',
        ),
        migrations.RemoveField(
            model_name='akun',
            name='nama_lengkap_en',
        ),
        migrations.RemoveField(
            model_name='akun',
            name='nama_lengkap_ind',
        ),
        migrations.RemoveField(
            model_name='dosen',
            name='nama_dosen_en',
        ),
        migrations.RemoveField(
            model_name='dosen',
            name='nama_dosen_ind',
        ),
        migrations.RemoveField(
            model_name='dosen',
            name='prodi_en',
        ),
        migrations.RemoveField(
            model_name='dosen',
            name='prodi_ind',
        ),
        migrations.RemoveField(
            model_name='fotowajah',
            name='keterangan_en',
        ),
        migrations.RemoveField(
            model_name='fotowajah',
            name='keterangan_ind',
        ),
        migrations.RemoveField(
            model_name='jenjang_pendidikan',
            name='nama_jenjang_en',
        ),
        migrations.RemoveField(
            model_name='jenjang_pendidikan',
            name='nama_jenjang_ind',
        ),
        migrations.RemoveField(
            model_name='kegiatan_pa',
            name='nama_kegiatan_en',
        ),
        migrations.RemoveField(
            model_name='kegiatan_pa',
            name='nama_kegiatan_ind',
        ),
        migrations.RemoveField(
            model_name='mahasiswa',
            name='jurusan_en',
        ),
        migrations.RemoveField(
            model_name='mahasiswa',
            name='jurusan_ind',
        ),
        migrations.RemoveField(
            model_name='mahasiswa',
            name='kelas_en',
        ),
        migrations.RemoveField(
            model_name='mahasiswa',
            name='kelas_ind',
        ),
        migrations.RemoveField(
            model_name='pengajuan_pendaftaran',
            name='alasan_penolakan_en',
        ),
        migrations.RemoveField(
            model_name='pengajuan_pendaftaran',
            name='alasan_penolakan_ind',
        ),
        migrations.RemoveField(
            model_name='semester',
            name='nama_semester_en',
        ),
        migrations.RemoveField(
            model_name='semester',
            name='nama_semester_ind',
        ),
        migrations.RemoveField(
            model_name='tahun_ajaran',
            name='nama_tahun_ajaran_en',
        ),
        migrations.RemoveField(
            model_name='tahun_ajaran',
            name='nama_tahun_ajaran_ind',
        ),
        migrations.AlterField(
            model_name='presensi',
            name='kegiatan_pa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.kegiatan_pa'),
        ),
    ]
