# Generated by Django 5.2.8 on 2026-02-21 15:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_remove_akun_first_name_en_remove_akun_first_name_ind_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='presensi',
            options={},
        ),
        migrations.AddField(
            model_name='presensi',
            name='terakhir_terdeteksi',
            field=models.TimeField(blank=True, null=True, verbose_name='Last Detected Time'),
        ),
        migrations.CreateModel(
            name='VerificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=False)),
                ('is_liveness_real', models.BooleanField(default=False)),
                ('failure_count', models.IntegerField(default=0)),
                ('mahasiswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.mahasiswa')),
                ('presensi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='verification_logs', to='accounts.presensi')),
            ],
            options={
                'verbose_name': 'Attendance',
                'verbose_name_plural': 'Attendances',
            },
        ),
    ]
