# Generated by Django 5.2.8 on 2026-02-21 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_presensi_options_presensi_terakhir_terdeteksi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='verificationlog',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='presensi/verification/', verbose_name='Verification Photo'),
        ),
    ]
