# Generated by Django 5.2.8 on 2026-02-23 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_verificationlog_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='presensi',
            name='failure_count',
            field=models.IntegerField(default=0, verbose_name='Failure Count'),
        ),
        migrations.AddField(
            model_name='presensi',
            name='last_verified_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last Verified At'),
        ),
        migrations.AddField(
            model_name='presensi',
            name='session_status',
            field=models.CharField(choices=[('active', 'Active'), ('verifying', 'Verifying'), ('auto_checkout', 'Auto Checked Out'), ('completed', 'Completed')], default='active', max_length=20, verbose_name='Session Status'),
        ),
    ]
