# Generated by Django 5.2.8 on 2026-02-23 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_presensi_failure_count_presensi_last_verified_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='verificationlog',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Presence Verification Log', 'verbose_name_plural': 'Presence Verification Logs'},
        ),
    ]
